name: python-312

on:
  push:
    branches:
      - master
  schedule:
    - cron: "42 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      LOCALE: zh_CN
      VERSION: "3.12"
    steps:
      - uses: actions/checkout@v3
      - name: Checkout CPython
        uses: actions/checkout@v3
        with:
          repository: 'python/cpython'
          ref: ${{env.VERSION}}
          path: cpython
      - name: Checkout Current Branch
        uses: actions/checkout@v3
        with:
          ref: ${{env.VERSION}}
          path: docs
      - name: prepare
        run: .github/scripts/prepare.sh
      - name: update
        run: .github/scripts/update.sh
        env:
          TX_TOKEN: ${{ secrets.TRANSIFEX_APIKEY }}
      - name: Restore doctrees Cache
        uses: actions/cache/restore@v3
        with:
          path: ./cpython/Doc/build/doctrees
          key: sphinx-cache-${{env.VERSION}}
      - name: build
        run: .github/scripts/build.sh
      - name: Save doctrees Cache
        uses: actions/cache/save@v3
        with:
          path: ./cpython/Doc/build/doctrees
          key: sphinx-cache-${{env.VERSION}}
      - name: commit
        run: .github/scripts/commit.sh
