name: python-37

on:
  push:
    branches:
      - master
  schedule:
    - cron: "53 * * * *"

jobs:
  sync:
    uses: ./.github/workflows/sync.yml
    with:
      version: "3.7"
    secrets: inherit