name: python-310

on:
  push:
    branches:
      - master
  schedule:
    - cron: "8 * * * *"

jobs:
  sync:
    uses: ./.github/workflows/sync.yml
    with:
      version: "3.10"
    secrets: inherit
    