name: python-39

on:
  push:
    branches:
      - master
  schedule:
    - cron: "14 * * * *"

jobs:
  sync:
    uses: ./.github/workflows/sync.yml
    with:
      version: "3.9"
    secrets: inherit
    